# Generated by Django 3.1.7 on 2021-04-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backenddb.job'),
        ),
        migrations.AddField(
            model_name='timecard',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backenddb.machine'),
        ),
    ]
