# Generated by Django 3.1.7 on 2021-04-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0002_auto_20210404_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
