# Generated by Django 3.1.7 on 2021-04-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0003_timecard_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecard',
            name='job',
        ),
        migrations.AddField(
            model_name='timecard',
            name='job',
            field=models.ManyToManyField(null=True, to='backenddb.Job'),
        ),
        migrations.RemoveField(
            model_name='timecard',
            name='machine',
        ),
        migrations.AddField(
            model_name='timecard',
            name='machine',
            field=models.ManyToManyField(null=True, to='backenddb.Machine'),
        ),
    ]
