# Generated by Django 3.1.7 on 2021-04-04 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0004_auto_20210404_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecard',
            name='job',
        ),
        migrations.AddField(
            model_name='timecard',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backenddb.job'),
        ),
        migrations.RemoveField(
            model_name='timecard',
            name='machine',
        ),
        migrations.AddField(
            model_name='timecard',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backenddb.machine'),
        ),
    ]
