# Generated by Django 3.1.7 on 2021-04-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0008_auto_20210405_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='job',
            field=models.ManyToManyField(to='backenddb.Job'),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='machine',
            field=models.ManyToManyField(to='backenddb.Machine'),
        ),
    ]
