# Generated by Django 3.1.7 on 2021-04-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0009_auto_20210405_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timecard',
            old_name='total_hours',
            new_name='total_job_hours',
        ),
        migrations.AddField(
            model_name='timecard',
            name='total_machine_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
